### ISSUE TITLE
ioDetailedStatus api value is undocumented

### ISSUE THREAD

**Issue by DDR0** [krontech/pychronos#33]
`cam-json get - <<< '["ioDetailedStatus"]'` works, yet is undocumented.

**Comment by oskirby** [comment]
After some refactoring, there should now be documentation available for ioDetailedStatus, which is really a collection of ioSourceStatus, ioOutputStatus and some other odds and ends that can be gleaned from the FPGA registers.

The biggest difference is that you can also get the time-since-last-edge detected for each of the input signals too.
